=== jordanwalsh23/ELK-Weather-Data/product.xsd
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="1.5.1">
  <xsd:annotation>
    <xsd:documentation>
      Filename : product.xsd Organisation : Australian Bureau of Meteorology Date : 12/10/2011 Description : Notes :
    </xsd:documentation>
  </xsd:annotation>
  <xsd:include schemaLocation="amoc.xsd"/>
  <xsd:element name="product" type="productType">
    <xsd:annotation>
      <xsd:documentation>
        This is the root element that is used to identify the XML data as PRODUCT XML.
      </xsd:documentation>
    </xsd:annotation>
  </xsd:element>
  <xsd:complexType name="productType">
    <xsd:sequence>
      <xsd:element name="amoc" type="amocType"/>
      <xsd:element name="warning" type="warningType" minOccurs="0"/>
      <xsd:element name="forecast" type="forecastType" minOccurs="0"/>
      <xsd:element name="warning-summaries" type="warning-summariesType" minOccurs="0"/>
      <xsd:element name="observations" type="observationsType" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="version" type="xsd:string" default="1.5"/>
  </xsd:complexType>
  <xsd:complexType name="warningType">
    <xsd:sequence>
      <xsd:element name="warning-info" type="warning-infoType"/>
      <xsd:element name="area" type="areaType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="warning-infoType">
    <xsd:sequence>
      <xsd:element name="text" type="text-elementType" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="forecastType">
    <xsd:sequence>
      <xsd:element name="area" type="areaType" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="observationsType">
    <xsd:sequence>
      <xsd:element name="station" type="stationType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="areaType">
    <xsd:sequence>
      <xsd:element name="warning-summary" type="warning-summaryType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="forecast-period" type="forecast-periodType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="hazard" type="hazardType" maxOccurs="unbounded" minOccurs="0"/>
      <xsd:element name="warning-group" type="warning-groupType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="aac" type="aacType" use="required"/>
    <xsd:attribute name="parent-aac" type="aacType" use="optional"/>
    <xsd:attribute name="description" type="xsd:string" use="required"/>
    <xsd:attribute name="type" type="xsd:string" use="required"/>
  </xsd:complexType>
  <xsd:complexType name="warning-summaryType" mixed="true">
    <xsd:sequence minOccurs="0">
      <xsd:element name="p" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="type" type="xsd:string" use="optional"/>
    <xsd:attribute name="product-identifier" type="identifierType" use="optional"/>
    <xsd:attribute name="product-url" type="xsd:anyURI" use="optional"/>
    <xsd:attribute name="start-time-utc" type="xsd:dateTime" use="required"/>
    <xsd:attribute name="start-time-local" type="xsd:dateTime" use="required"/>
    <xsd:attribute name="end-time-utc" type="xsd:dateTime" use="required"/>
    <xsd:attribute name="end-time-local" type="xsd:dateTime" use="required"/>
  </xsd:complexType>
  <xsd:complexType name="forecast-periodType">
    <xsd:sequence>
      <xsd:element name="warning-summary" type="warning-summaryType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="element" type="elementType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="text" type="text-elementType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="hazard" type="periodicHazardType" maxOccurs="unbounded" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="index" use="optional" type="xsd:nonNegativeInteger"/>
    <xsd:attribute name="start-time-utc" type="xsd:dateTime" use="optional"/>
    <xsd:attribute name="start-time-local" type="xsd:dateTime" use="required"/>
    <xsd:attribute name="end-time-utc" type="xsd:dateTime" use="optional"/>
    <xsd:attribute name="end-time-local" type="xsd:dateTime" use="required"/>
    <xsd:attribute name="end-date-local" type="xsd:dateTime" use="optional"/>
  </xsd:complexType>
  <xsd:complexType name="observation-periodType">
    <xsd:sequence>
      <xsd:element name="level" type="levelType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="element" type="elementType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="index" use="optional" type="xsd:nonNegativeInteger"/>
    <xsd:attribute name="time-utc" type="xsd:dateTime" use="optional"/>
    <xsd:attribute name="time-local" type="xsd:dateTime" use="required"/>
    <xsd:attribute name="wind-src" type="xsd:string" use="optional"/>
  </xsd:complexType>
  <xsd:complexType name="text-elementType" mixed="true">
    <xsd:sequence minOccurs="0">
      <xsd:element name="p" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="type" type="xsd:string" use="required"/>
  </xsd:complexType>
  <xsd:complexType name="elementType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="type" type="xsd:string" use="required"/>
        <xsd:attribute name="units" type="xsd:string" use="optional"/>
        <xsd:attribute name="instance" type="xsd:string" use="optional"/>
        <xsd:attribute name="sequence" use="optional" type="xsd:nonNegativeInteger"/>
        <xsd:attribute name="duration" use="optional" type="xsd:nonNegativeInteger"/>
        <xsd:attribute name="time-utc" type="xsd:dateTime" use="optional"/>
        <xsd:attribute name="time-local" type="xsd:dateTime" use="optional"/>
        <xsd:attribute name="start-time-utc" type="xsd:dateTime" use="optional"/>
        <xsd:attribute name="start-time-local" type="xsd:dateTime" use="optional"/>
        <xsd:attribute name="end-time-utc" type="xsd:dateTime" use="optional"/>
        <xsd:attribute name="end-time-local" type="xsd:dateTime" use="optional"/>
        <xsd:attribute name="start-month" type="xsd:string" use="optional"/>
        <xsd:attribute name="end-month" type="xsd:string" use="optional"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name="warning-summariesType" mixed="true">
    <xsd:sequence minOccurs="0">
      <xsd:element name="forecast-area" type="areaType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="warning-groupType">
    <xsd:sequence>
      <xsd:element name="coverage-area" type="areaType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="priority-order" use="required" type="xsd:nonNegativeInteger"/>
    <xsd:attribute name="type" type="xsd:string" use="required"/>
  </xsd:complexType>
  <xsd:complexType name="stationType">
    <xsd:sequence>
      <xsd:element name="period" type="observation-periodType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="bom-id" type="xsd:string" use="optional"/>
    <xsd:attribute name="wmo-id" type="xsd:string" use="optional"/>
    <xsd:attribute name="aviation-id" type="xsd:string" use="optional"/>
    <xsd:attribute name="description" type="xsd:string" use="required"/>
    <xsd:attribute name="tz" type="xsd:string" use="required"/>
    <xsd:attribute name="stn-name" type="xsd:string" use="optional"/>
    <xsd:attribute name="stn-height" type="xsd:float" use="optional"/>
    <xsd:attribute name="type" type="xsd:string" use="optional"/>
    <xsd:attribute name="owner" type="xsd:string" use="optional"/>
    <xsd:attribute name="lat" type="xsd:float" use="required"/>
    <xsd:attribute name="lon" type="xsd:float" use="required"/>
    <xsd:attribute name="forecast-district-id" type="xsd:string" use="required"/>
  </xsd:complexType>
  <xsd:complexType name="levelType">
    <xsd:sequence minOccurs="0">
      <xsd:element name="element" type="elementType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="index" use="optional" type="xsd:nonNegativeInteger"/>
    <xsd:attribute name="type" type="xsd:string" use="required"/>
  </xsd:complexType>
</xsd:schema>

=== jordanwalsh23/ELK-Weather-Data/download/IDT13600.xml
<?xml version="1.0" encoding="utf-8"?> 
<product version="1.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.bom.gov.au/schema/v1.5/product.xsd"><amoc><source><sender>Australian Government Bureau of Meteorology</sender><region>Tasmania</region><office>TASRO</office><copyright>http://www.bom.gov.au/other/copyright.shtml</copyright><disclaimer>http://www.bom.gov.au/other/disclaimer.shtml</disclaimer></source><identifier>IDT13600</identifier><issue-time-utc>2016-03-18T18:23:48Z</issue-time-utc><issue-time-local tz="EDT">2016-03-19T05:23:48+11:00</issue-time-local><sent-time>2016-03-18T18:23:48Z</sent-time><expiry-time>2016-03-19T18:23:48Z</expiry-time><validity-bgn-time-local tz="EDT">2016-03-19T00:00:00+11:00</validity-bgn-time-local><validity-end-time-local tz="EDT">2016-03-25T23:59:59+11:00</validity-end-time-local><next-routine-issue-time-utc>2016-03-19T05:20:00Z</next-routine-issue-time-utc><next-routine-issue-time-local tz="EDT">2016-03-19T16:20:00+11:00</next-routine-issue-time-local><status>O</status><service>WSP</service><sub-service>FCT</sub-service><product-type>F</product-type><phase>NEW</phase></amoc><forecast><area aac="TAS_FA001" description="Tasmania" type="region"><forecast-period start-time-local="2016-03-19T05:23:49+11:00" end-time-local="2016-03-19T05:23:49+11:00" start-time-utc="2016-03-18T18:23:49Z" end-time-utc="2016-03-18T18:23:49Z"><text type="warning_summary_footer">For latest warnings go to www.bom.gov.au, subscribe to RSS feeds, call 1300-659-216* or listen for warnings on relevant TV and radio broadcasts.</text><text type="product_footer">* Calls to 1300 numbers cost around 27.5c incl. GST, higher from mobiles or public phones.</text></forecast-period></area><area aac="TAS_ME001" description="Hobart" type="metropolitan" parent-aac="TAS_FA001"><forecast-period index="0" start-time-local="2016-03-19T00:00:00+11:00" end-time-local="2016-03-20T00:00:00+11:00" start-time-utc="2016-03-18T13:00:00Z" end-time-utc="2016-03-19T13:00:00Z"><text type="forecast">Cloudy. Medium (40%) chance of showers, becoming less likely this afternoon and evening. Winds south to southwesterly 25 to 35 km/h.</text><text type="fire_danger">Low-Moderate</text><text type="uv_alert">UV Alert from 10:40 am to 4:00 pm, UV Index predicted to reach 6 [High]</text></forecast-period><forecast-period index="1" start-time-local="2016-03-20T00:00:00+11:00" end-time-local="2016-03-21T00:00:00+11:00" start-time-utc="2016-03-19T13:00:00Z" end-time-utc="2016-03-20T13:00:00Z"><text type="forecast">Partly cloudy. Light winds becoming southeasterly 15 to 20 km/h in the early afternoon then becoming light in the evening.</text></forecast-period><forecast-period index="2" start-time-local="2016-03-21T00:00:00+11:00" end-time-local="2016-03-22T00:00:00+11:00" start-time-utc="2016-03-20T13:00:00Z" end-time-utc="2016-03-21T13:00:00Z"><text type="forecast">Partly cloudy. Slight (20%) chance of a shower. Light winds.</text></forecast-period><forecast-period index="3" start-time-local="2016-03-22T00:00:00+11:00" end-time-local="2016-03-23T00:00:00+11:00" start-time-utc="2016-03-21T13:00:00Z" end-time-utc="2016-03-22T13:00:00Z"><text type="forecast">Sunny. Light winds becoming northeast to southeasterly 15 to 25 km/h during the afternoon then becoming light during the evening.</text></forecast-period><forecast-period index="4" start-time-local="2016-03-23T00:00:00+11:00" end-time-local="2016-03-24T00:00:00+11:00" start-time-utc="2016-03-22T13:00:00Z" end-time-utc="2016-03-23T13:00:00Z"><text type="forecast">Partly cloudy. Slight (30%) chance of a shower, most likely later in the day. Light winds.</text></forecast-period><forecast-period index="5" start-time-local="2016-03-24T00:00:00+11:00" end-time-local="2016-03-25T00:00:00+11:00" start-time-utc="2016-03-23T13:00:00Z" end-time-utc="2016-03-24T13:00:00Z"><text type="forecast">Partly cloudy. Slight (30%) chance of a shower. Light winds.</text></forecast-period><forecast-period index="6" start-time-local="2016-03-25T00:00:00+11:00" end-time-local="2016-03-26T00:00:00+11:00" start-time-utc="2016-03-24T13:00:00Z" end-time-utc="2016-03-25T13:00:00Z"><text type="forecast">Cloudy. Slight (30%) chance of a shower. Light winds becoming westerly 15 to 20 km/h during the day.</text></forecast-period></area><area aac="TAS_PT021" description="Hobart" type="location" parent-aac="TAS_ME001"><forecast-period index="0" start-time-local="2016-03-19T05:00:00+11:00" end-time-local="2016-03-20T00:00:00+11:00" start-time-utc="2016-03-18T18:00:00Z" end-time-utc="2016-03-19T13:00:00Z"><element type="forecast_icon_code">11</element><element type="precipitation_range">0 to 1 mm</element><element type="air_temperature_maximum" units="Celsius">15</element><text type="precis">Shower or two.</text><text type="probability_of_precipitation">50%</text></forecast-period><forecast-period index="1" start-time-local="2016-03-20T00:00:00+11:00" end-time-local="2016-03-21T00:00:00+11:00" start-time-utc="2016-03-19T13:00:00Z" end-time-utc="2016-03-20T13:00:00Z"><element type="forecast_icon_code">3</element><element type="precipitation_range">0 mm</element><element type="air_temperature_minimum" units="Celsius">8</element><element type="air_temperature_maximum" units="Celsius">18</element><text type="precis">Partly cloudy.</text><text type="probability_of_precipitation">10%</text></forecast-period><forecast-period index="2" start-time-local="2016-03-21T00:00:00+11:00" end-time-local="2016-03-22T00:00:00+11:00" start-time-utc="2016-03-20T13:00:00Z" end-time-utc="2016-03-21T13:00:00Z"><element type="forecast_icon_code">3</element><element type="precipitation_range">0 mm</element><element type="air_temperature_minimum" units="Celsius">10</element><element type="air_temperature_maximum" units="Celsius">19</element><text type="precis">Partly cloudy.</text><text type="probability_of_precipitation">20%</text></forecast-period><forecast-period index="3" start-time-local="2016-03-22T00:00:00+11:00" end-time-local="2016-03-23T00:00:00+11:00" start-time-utc="2016-03-21T13:00:00Z" end-time-utc="2016-03-22T13:00:00Z"><element type="forecast_icon_code">1</element><element type="precipitation_range">0 mm</element><element type="air_temperature_minimum" units="Celsius">11</element><element type="air_temperature_maximum" units="Celsius">22</element><text type="precis">Sunny.</text><text type="probability_of_precipitation">0%</text></forecast-period><forecast-period index="4" start-time-local="2016-03-23T00:00:00+11:00" end-time-local="2016-03-24T00:00:00+11:00" start-time-utc="2016-03-22T13:00:00Z" end-time-utc="2016-03-23T13:00:00Z"><element type="forecast_icon_code">17</element><element type="precipitation_range">0 to 0.4 mm</element><element type="air_temperature_minimum" units="Celsius">13</element><element type="air_temperature_maximum" units="Celsius">22</element><text type="precis">Possible shower.</text><text type="probability_of_precipitation">30%</text></forecast-period><forecast-period index="5" start-time-local="2016-03-24T00:00:00+11:00" end-time-local="2016-03-25T00:00:00+11:00" start-time-utc="2016-03-23T13:00:00Z" end-time-utc="2016-03-24T13:00:00Z"><element type="forecast_icon_code">17</element><element type="precipitation_range">0 to 2 mm</element><element type="air_temperature_minimum" units="Celsius">12</element><element type="air_temperature_maximum" units="Celsius">19</element><text type="precis">Possible shower.</text><text type="probability_of_precipitation">30%</text></forecast-period><forecast-period index="6" start-time-local="2016-03-25T00:00:00+11:00" end-time-local="2016-03-26T00:00:00+11:00" start-time-utc="2016-03-24T13:00:00Z" end-time-utc="2016-03-25T13:00:00Z"><element type="forecast_icon_code">17</element><element type="precipitation_range">0 to 0.2 mm</element><element type="air_temperature_minimum" units="Celsius">11</element><element type="air_temperature_maximum" units="Celsius">20</element><text type="precis">Possible shower.</text><text type="probability_of_precipitation">30%</text></forecast-period></area><area aac="TAS_PT039" description="Kunanyi/Mount Wellington" type="location" parent-aac="TAS_ME001"><forecast-period index="0" start-time-local="2016-03-19T05:00:00+11:00" end-time-local="2016-03-20T00:00:00+11:00" start-time-utc="2016-03-18T18:00:00Z" end-time-utc="2016-03-19T13:00:00Z"><element type="air_temperature_maximum" units="Celsius">5</element></forecast-period></area><area aac="TAS_PT109" description="Bellerive" type="location" parent-aac="TAS_ME001"><forecast-period index="0" start-time-local="2016-03-19T05:00:00+11:00" end-time-local="2016-03-20T00:00:00+11:00" start-time-utc="2016-03-18T18:00:00Z" end-time-utc="2016-03-19T13:00:00Z"><element type="air_temperature_maximum" units="Celsius">15</element></forecast-period></area><area aac="TAS_PT108" description="Glenorchy" type="location" parent-aac="TAS_ME001"><forecast-period index="0" start-time-local="2016-03-19T05:00:00+11:00" end-time-local="2016-03-20T00:00:00+11:00" start-time-utc="2016-03-18T18:00:00Z" end-time-utc="2016-03-19T13:00:00Z"><element type="air_temperature_maximum" units="Celsius">15</element></forecast-period></area><area aac="TAS_PT110" description="Kingston" type="location" parent-aac="TAS_ME001"><forecast-period index="0" start-time-local="2016-03-19T05:00:00+11:00" end-time-local="2016-03-20T00:00:00+11:00" start-time-utc="2016-03-18T18:00:00Z" end-time-utc="2016-03-19T13:00:00Z"><element type="air_temperature_maximum" units="Celsius">15</element></forecast-period></area></forecast></product>

=== jordanwalsh23/ELK-Weather-Data/download/IDQ10611.xml
<?xml version="1.0" encoding="utf-8"?> 
<product version="1.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.bom.gov.au/schema/v1.5/product.xsd"><amoc><source><sender>Australian Government Bureau of Meteorology</sender><region>Queensland</region><office>QLDRO</office><copyright>http://www.bom.gov.au/other/copyright.shtml</copyright><disclaimer>http://www.bom.gov.au/other/disclaimer.shtml</disclaimer></source><identifier>IDQ10611</identifier><issue-time-utc>2016-03-18T18:50:00Z</issue-time-utc><issue-time-local tz="EST">2016-03-19T04:50:00+10:00</issue-time-local><sent-time>2016-03-18T18:50:24Z</sent-time><expiry-time>2016-03-19T18:50:00Z</expiry-time><validity-bgn-time-local tz="EST">2016-03-19T00:00:00+10:00</validity-bgn-time-local><validity-end-time-local tz="EST">2016-03-25T23:59:59+10:00</validity-end-time-local><next-routine-issue-time-utc>2016-03-19T06:20:00Z</next-routine-issue-time-utc><next-routine-issue-time-local tz="EST">2016-03-19T16:20:00+10:00</next-routine-issue-time-local><status>O</status><service>WSP</service><sub-service>FCT</sub-service><product-type>F</product-type><phase>NEW</phase></amoc><forecast><area aac="QLD_FA001" description="Queensland" type="region"><forecast-period start-time-local="2016-03-19T04:50:24+10:00" end-time-local="2016-03-19T04:50:24+10:00" start-time-utc="2016-03-18T18:50:24Z" end-time-utc="2016-03-18T18:50:24Z"><text type="warning_summary_footer">For latest warnings go to www.bom.gov.au, subscribe to RSS feeds, call 1300-659-219* or listen for warnings on relevant TV and radio broadcasts.</text><text type="product_footer">* Calls to 1300 numbers cost around 27.5c incl. GST, higher from mobiles or public phones.</text></forecast-period></area><area aac="QLD_ME002" description="Sunshine Coast" type="metropolitan" parent-aac="QLD_FA001"><forecast-period index="0" start-time-local="2016-03-19T00:00:00+10:00" end-time-local="2016-03-20T00:00:00+10:00" start-time-utc="2016-03-18T14:00:00Z" end-time-utc="2016-03-19T14:00:00Z"><text type="forecast">Partly cloudy. High (70%) chance of showers from late this morning. The chance of a thunderstorm this afternoon, possibly severe. Light winds becoming southeasterly 15 to 25 km/h in the late afternoon.</text><text type="fire_danger">Low-Moderate</text><text type="uv_alert">UV Alert from 8:20 am to 3:20 pm, UV Index predicted to reach 11 [Extreme]</text></forecast-period><forecast-period index="1" start-time-local="2016-03-20T00:00:00+10:00" end-time-local="2016-03-21T00:00:00+10:00" start-time-utc="2016-03-19T14:00:00Z" end-time-utc="2016-03-20T14:00:00Z"><text type="forecast">Cloudy. Medium (60%) chance of showers, most likely in the morning and afternoon. The chance of a thunderstorm about the hinterland in the afternoon. Winds southeasterly 15 to 25 km/h.</text></forecast-period><forecast-period index="2" start-time-local="2016-03-21T00:00:00+10:00" end-time-local="2016-03-22T00:00:00+10:00" start-time-utc="2016-03-20T14:00:00Z" end-time-utc="2016-03-21T14:00:00Z"><text type="forecast">Partly cloudy. Slight (30%) chance of a shower. Winds southeasterly 15 to 25 km/h.</text></forecast-period><forecast-period index="3" start-time-local="2016-03-22T00:00:00+10:00" end-time-local="2016-03-23T00:00:00+10:00" start-time-utc="2016-03-21T14:00:00Z" end-time-utc="2016-03-22T14:00:00Z"><text type="forecast">Partly cloudy. Medium (60%) chance of showers, most likely in the morning and afternoon. The chance of a thunderstorm in the afternoon and evening. Winds southeasterly 15 to 25 km/h becoming light during the evening.</text></forecast-period><forecast-period index="4" start-time-local="2016-03-23T00:00:00+10:00" end-time-local="2016-03-24T00:00:00+10:00" start-time-utc="2016-03-22T14:00:00Z" end-time-utc="2016-03-23T14:00:00Z"><text type="forecast">Mostly sunny. Slight (20%) chance of a shower. Light winds becoming easterly 15 to 20 km/h during the day.</text></forecast-period><forecast-period index="5" start-time-local="2016-03-24T00:00:00+10:00" end-time-local="2016-03-25T00:00:00+10:00" start-time-utc="2016-03-23T14:00:00Z" end-time-utc="2016-03-24T14:00:00Z"><text type="forecast">Partly cloudy. Slight (30%) chance of a shower. Light winds becoming easterly 15 to 20 km/h during the day.</text></forecast-period><forecast-period index="6" start-time-local="2016-03-25T00:00:00+10:00" end-time-local="2016-03-26T00:00:00+10:00" start-time-utc="2016-03-24T14:00:00Z" end-time-utc="2016-03-25T14:00:00Z"><text type="forecast">Partly cloudy. Slight (20%) chance of a shower. Light winds becoming northeasterly 15 to 20 km/h during the day.</text></forecast-period></area><area aac="QLD_PT002" description="Maroochydore" type="location" parent-aac="QLD_ME002"><forecast-period index="0" start-time-local="2016-03-19T05:00:00+10:00" end-time-local="2016-03-20T00:00:00+10:00" start-time-utc="2016-03-18T19:00:00Z" end-time-utc="2016-03-19T14:00:00Z"><element type="forecast_icon_code">16</element><element type="precipitation_range">1 to 6 mm</element><element type="air_temperature_maximum" units="Celsius">32</element><text type="precis">Shower or two. Possible storm.</text><text type="probability_of_precipitation">70%</text></forecast-period><forecast-period index="1" start-time-local="2016-03-20T00:00:00+10:00" end-time-local="2016-03-21T00:00:00+10:00" start-time-utc="2016-03-19T14:00:00Z" end-time-utc="2016-03-20T14:00:00Z"><element type="forecast_icon_code">11</element><element type="precipitation_range">1 to 8 mm</element><element type="air_temperature_minimum" units="Celsius">22</element><element type="air_temperature_maximum" units="Celsius">29</element><text type="precis">Shower or two.</text><text type="probability_of_precipitation">60%</text></forecast-period><forecast-period index="2" start-time-local="2016-03-21T00:00:00+10:00" end-time-local="2016-03-22T00:00:00+10:00" start-time-utc="2016-03-20T14:00:00Z" end-time-utc="2016-03-21T14:00:00Z"><element type="forecast_icon_code">17</element><element type="precipitation_range">0 to 1 mm</element><element type="air_temperature_minimum" units="Celsius">21</element><element type="air_temperature_maximum" units="Celsius">29</element><text type="precis">Possible shower.</text><text type="probability_of_precipitation">40%</text></forecast-period><forecast-period index="3" start-time-local="2016-03-22T00:00:00+10:00" end-time-local="2016-03-23T00:00:00+10:00" start-time-utc="2016-03-21T14:00:00Z" end-time-utc="2016-03-22T14:00:00Z"><element type="forecast_icon_code">11</element><element type="precipitation_range">1 to 5 mm</element><element type="air_temperature_minimum" units="Celsius">20</element><element type="air_temperature_maximum" units="Celsius">29</element><text type="precis">Shower or two.</text><text type="probability_of_precipitation">60%</text></forecast-period><forecast-period index="4" start-time-local="2016-03-23T00:00:00+10:00" end-time-local="2016-03-24T00:00:00+10:00" start-time-utc="2016-03-22T14:00:00Z" end-time-utc="2016-03-23T14:00:00Z"><element type="forecast_icon_code">17</element><element type="precipitation_range">0 to 0.2 mm</element><element type="air_temperature_minimum" units="Celsius">20</element><element type="air_temperature_maximum" units="Celsius">30</element><text type="precis">Possible shower.</text><text type="probability_of_precipitation">30%</text></forecast-period><forecast-period index="5" start-time-local="2016-03-24T00:00:00+10:00" end-time-local="2016-03-25T00:00:00+10:00" start-time-utc="2016-03-23T14:00:00Z" end-time-utc="2016-03-24T14:00:00Z"><element type="forecast_icon_code">17</element><element type="precipitation_range">0 to 0.4 mm</element><element type="air_temperature_minimum" units="Celsius">20</element><element type="air_temperature_maximum" units="Celsius">30</element><text type="precis">Possible shower.</text><text type="probability_of_precipitation">30%</text></forecast-period><forecast-period index="6" start-time-local="2016-03-25T00:00:00+10:00" end-time-local="2016-03-26T00:00:00+10:00" start-time-utc="2016-03-24T14:00:00Z" end-time-utc="2016-03-25T14:00:00Z"><element type="forecast_icon_code">3</element><element type="precipitation_range">0 mm</element><element type="air_temperature_minimum" units="Celsius">21</element><element type="air_temperature_maximum" units="Celsius">31</element><text type="precis">Partly cloudy.</text><text type="probability_of_precipitation">20%</text></forecast-period></area><area aac="QLD_PT053" description="Caloundra" type="location" parent-aac="QLD_ME002"><forecast-period index="0" start-time-local="2016-03-19T05:00:00+10:00" end-time-local="2016-03-20T00:00:00+10:00" start-time-utc="2016-03-18T19:00:00Z" end-time-utc="2016-03-19T14:00:00Z"><element type="air_temperature_maximum" units="Celsius">33</element></forecast-period></area><area aac="QLD_PT122" description="Maleny" type="location" parent-aac="QLD_ME002"><forecast-period index="0" start-time-local="2016-03-19T05:00:00+10:00" end-time-local="2016-03-20T00:00:00+10:00" start-time-utc="2016-03-18T19:00:00Z" end-time-utc="2016-03-19T14:00:00Z"><element type="air_temperature_maximum" units="Celsius">31</element></forecast-period></area><area aac="QLD_PT136" description="Nambour" type="location" parent-aac="QLD_ME002"><forecast-period index="0" start-time-local="2016-03-19T05:00:00+10:00" end-time-local="2016-03-20T00:00:00+10:00" start-time-utc="2016-03-18T19:00:00Z" end-time-utc="2016-03-19T14:00:00Z"><element type="air_temperature_maximum" units="Celsius">33</element></forecast-period></area><area aac="QLD_PT138" description="Noosa Heads" type="location" parent-aac="QLD_ME002"><forecast-period index="0" start-time-local="2016-03-19T05:00:00+10:00" end-time-local="2016-03-20T00:00:00+10:00" start-time-utc="2016-03-18T19:00:00Z" end-time-utc="2016-03-19T14:00:00Z"><element type="air_temperature_maximum" units="Celsius">31</element></forecast-period></area></forecast></product>
